### ISSUE TITLE
Code for extract test score 

### ISSUE THREAD

**Issue by wzmsltw** [wanglimin/UntrimmedNet#10]
Hi，Limin.
I want to reproduce the result of temporal action detection. I found following file is needed.
('~/code/temporal-segment-networks/THUMOS14_evalkit_20150930/test_score.mat')
I guess this file is too big for share. So can you share codes or scripts used for extracting "test score" file? Since current codes are used for video-level action recognition.
Thanks!

**Comment by wanglimin** [comment]
You could refer to the TSN code on how to extract test score:

https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/eval_net.py#L64

**Comment by wzmsltw** [comment]
Ok. Thanks.
