### ISSUE TITLE
How to implement L1-normorlization for label vectors during the training process?

### ISSUE THREAD

**Issue by jx-zhong-for-academic-purpose** [wanglimin/UntrimmedNet#12]
Thank you very much, I benefit a lot from reading your codes. In Section 3.3, you have pointed out the L1-norm is conducted upon the label vector. However, in the code https://github.com/yjxiong/caffe/blob/untrimmednet/src/caffe/layers/sequence_data_layer.cpp (line42: infile >> filename >> length >> label), it seems that the sequence_data_layer allows only one label for each video_source. Therefore,  how do you implement L1-normorlization for label vectors during the training process?

**Comment by jx-zhong-for-academic-purpose** [comment]
Another question: In the "Action detection" part of Section 4,  you have said "we perform test every 15 frames".  I have tried this by modifing the train_val proto and sequence_data_layer.cpp, and running on K80 GPUs. To my disappointment, it is out of GPU memory. So I would like to know how to implement this, is it by preprocessing the source images and testing them via deploy proto files?

**Comment by wanglimin** [comment]
For your first question, if a video has multiple labels, we will duplicate this video several times in our train file list and each time it has  a single label. Therefore, for the whole training process, it is equivalent to normalizing the label with l1 norm.

For your second question, we just test them via deploy proto files.

**Comment by jx-zhong-for-academic-purpose** [comment]
Thanks, exciting implementation! For the second question, are there any source codes for reference?

**Comment by wanglimin** [comment]
You could refer to the TSN code:

https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/eval_net.py#L64

**Comment by jx-zhong-for-academic-purpose** [comment]
OK. Thank you for your prompt reply~
