### ISSUE TITLE
THUMOS 14 Input Resolution

### ISSUE THREAD

**Issue by jonishungry** [wanglimin/UntrimmedNet#13]
The THUMOS proto file indicates that the network takes 224x224 as input but the THUMOS 14 test video files have a resolution of 320x180. 

What operations did you perform to get a 224 crop?

**Comment by wanglimin** [comment]
We resize the resolution THUMOS videos to 256*340.

**Comment by jonishungry** [comment]
Thanks!

**Comment by junmuzi** [comment]
Hi Limin,

What the frame rate(that is fps) when you used to extract frames from videos in Thumos14 and anet1.2 dataset, respectively?  Thanks.

**Comment by wanglimin** [comment]
For action recognition，we sample 1 frame every 30 frames. For action detection, we sample 1 frame  every 15 frames.

**Comment by junmuzi** [comment]
Hi Limin,

Sorry, I want to know the framerate when decompress a video. 
e.g: ffmpeg -i  aaa.avi -r $framerate  ./image_%04d.jpg 
As above show, I want to know the value of "$framerate" in your paper. 
Thank you very much.

**Comment by wanglimin** [comment]
I did not change the frame rate when decoding video into images. I use the original frame rate.

**Comment by junmuzi** [comment]
Hi Limin,

Which code could show you sample 1 frame every 15 frames for action detection? I have double checked your  code sequence_data_layer.cpp and function ReadSegmentFlowToDatum, do not find anywhere to show you sample 1 frame every 15 frames. 

I am so confused as you use the original frame rate to decoding video into images. In my original thought, I think you have changed the frame rate to sample 1 frame every 15 frames when decoding video. Seems I am wrong. Could you give some explanations?  

Thank you very much.

**Comment by junmuzi** [comment]
@wanglimin

**Comment by wanglimin** [comment]
For training  we did not down sample video and train on the original frame rate. For testing, we down sample for efficiency and we just test every 30 or 15 frames.
