### ISSUE TITLE
About the detection test

### ISSUE THREAD

**Issue by junfengluo** [wanglimin/UntrimmedNet#14]
Hi, Limin:
Can you help me with the following questions?
1, I want to get the attention of each frame which shows in your paper in figure 6, so how can I do it ？
2, In the detection test, what the file "test_score.mat" in "thumos_detection.m" means, if it is same with "video_scores" in "eval_net.py" of TSN, then how to define the flow_test_attention and rgb_test_attention in "thumos_detection.m" at 6# and 12# which are not calculated in TSN.
3, Do you have the python code to share?

**Comment by wanglimin** [comment]
First, there is slight difference with TSN. In untrimmednet, you need to output the attention score as well, and the attention is defined at:

https://github.com/wanglimin/UntrimmedNet/blob/master/models/spatial_untrimmednet_soft_bn_inception_train_val.prototxt#L813

So, you could get video score and attention at the same time. You could modify the TSN code to get two scores in a easy way.

**Comment by junfengluo** [comment]
Thanks very much.

**Comment by junmuzi** [comment]
Hi Limin,
fc-attention layer in [1] let me know this is soft selection, but what layer in [2] denote hard selection? Thank you very much.
[1]https://github.com/wanglimin/UntrimmedNet/blob/master/models/spatial_untrimmednet_soft_bn_inception_train_val.prototxt#L813
[2]https://github.com/wanglimin/UntrimmedNet/blob/master/models/spatial_untrimmednet_hard_bn_inception_train_val.prototxt

**Comment by wanglimin** [comment]
Hard selection is performed by top-k pooling and it is implemented by a reduction layer:
https://github.com/wanglimin/UntrimmedNet/blob/master/models/spatial_untrimmednet_hard_bn_inception_train_val.prototxt#L810
