### ISSUE TITLE
How many frames sampled every 15 frames in action detection processes?

### ISSUE THREAD

**Issue by jx-zhong-for-academic-purpose** [wanglimin/UntrimmedNet#15]
In Section 4 of your paper, you said "For more precise localization, we perform test every 15 frames ". ATT,  I am wondering how many frames sampled every 15 frames in action detection processes, is it that the same as action recognition (i.e. 1 frame of rgb and 5 frames of flow) ?

**Comment by jx-zhong-for-academic-purpose** [comment]
Another question: What is the fusion weight on untrimmednet between the rgb stream and flow stream, 1:1.5 (as TSN in ECCV16) or 1:1(as the journal version)? Thank you for taking the time to read my issue~

**Comment by junfengluo** [comment]
1, I think it means every 15 frames like 1, 15, 30, 45, 60...
2, The fusion weight is 1:1 with is shown "thumos_detection.m 15#".

**Comment by junfengluo** [comment]
1, I think it means every 15 frames like 1, 15, 30, 45, 60...
2, The fusion weight is 1:1 which is shown in "thumos_detection.m 15#".

**Comment by wanglimin** [comment]
The understanding of @junfengluo is correct. For detection, the the number of sampled frames is the same with action recognition, i.e. 1 frame rgb and 5 frame optical flow.

**Comment by jx-zhong-for-academic-purpose** [comment]
OK. Thanks.
