### ISSUE TITLE
About the Pre-trained caffemodel only on ActivityNet_v1.2  training set.

### ISSUE THREAD

**Issue by JacobKong** [wanglimin/UntrimmedNet#16]
Dear Limin Wang:

Thanks for your awesome work. 

I am wondering the pre-trained ActivityNet_1.2 caffemodels that you provided are trained on training+validation datasets or just the training set?

If it is the former, would you please provide the caffemodel that only pre-trained on ActivityNet_1.2 training set？

Looking forward to your reply!

Thanks a lot!

**Comment by wanglimin** [comment]
We released the models trained on the train+val set. The model trained on train set only will be released soon.

**Comment by JacobKong** [comment]
Really hope that you can release the model as soon as possible!
Thanks a lot!

**Comment by JacobKong** [comment]
Sorry to bother again! I just really need to model that is trained on train set only to do some experiments these days.
So, would you please release the model as soon as possible. That's means a lot!
Thank you very much!

**Comment by wanglimin** [comment]
You could download them from:

http://people.ee.ethz.ch/~limwang/anet_model/

**Comment by JacobKong** [comment]
Thanks a lot! Really means something to me!

**Comment by AmoseKang** [comment]
Hello, I can not visit the link you provided before. Can you please upload a model again?
