### ISSUE TITLE
problem about downloading the pretrained model 

### ISSUE THREAD

**Issue by suhaisheng** [wanglimin/UntrimmedNet#17]
hello, there is something wrong with your server where hold the pretrained model,so that  i can not connect to it. and can you share your test code for generating the  test_score.mat? thx very much!

**Comment by wanglimin** [comment]
You could refer to the TSN code on how to extract test score:

https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/eval_net.py#L64

**Comment by wanglimin** [comment]
These models could be downloaded now.
