### ISSUE TITLE
"caffe.LayerParameter" has no field named "sequence_data_param"

### ISSUE THREAD

**Issue by junmuzi** [wanglimin/UntrimmedNet#20]
Seem this version of cafffe(https://github.com/yjxiong/caffe.git) does not have  "sequence_data_param", could anyone tell me which caffe version should I using? Thanks. 

Error like follows:
\# sh spatial_untrimmednet_soft_bn_inception_run.sh
...
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 11:23: Message type "caffe.LayerParameter" has no field named "sequence_data_param".
F1126 16:51:34.954509 18856 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ../models/spatial_untrimmednet_soft_bn_inception_train_val.prototxt
\*** Check failure stack trace: ***
    @     0x7f51c72bf5cd  google::LogMessage::Fail()
    @     0x7f51c72c1433  google::LogMessage::SendToLog()
    @     0x7f51c72bf15b  google::LogMessage::Flush()
    @     0x7f51c72c1e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f51c77b30f1  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f51c7784baf  caffe::Solver<>::InitTrainNet()
    @     0x7f51c7785dbe  caffe::Solver<>::Init()
    @     0x7f51c7785f86  caffe::Solver<>::Solver()
    @           0x40fec0  caffe::GetSolver<>()
    @           0x408103  train()
    @           0x405eb0  main
    @     0x7f51c62dd830  __libc_start_main
    @           0x4063c9  _start
    @              (nil)  (unknown)
Aborted (core dumped)
Done.

**Comment by wanglimin** [comment]
You need to use the untrimmednet branch:

https://github.com/yjxiong/caffe/tree/untrimmednet

**Comment by junmuzi** [comment]
Thank you very much @wanglimin.
