### ISSUE TITLE
issue about the test_window_shot_list on thumos14

### ISSUE THREAD

**Issue by suhaisheng** [wanglimin/UntrimmedNet#21]
Can you provide a sample of detected shot boudary on the thumos14 for test set.I would appreciate it very much.

**Comment by wanglimin** [comment]
Please see the folder： data/thumos14/val_window_shot/

**Comment by wanglimin** [comment]
It is on the val data.

**Comment by suhaisheng** [comment]
But it is only the shot for validation videos, do you have the one for test videos,which contain 1574 untrimmed videos.THX very much!

**Comment by wanglimin** [comment]
I do not have shot files for test videos because we did not extract shot when testing UntrimmedNet models.
