### ISSUE TITLE
The Number of Flow Frames and RGB Frames

### ISSUE THREAD

**Issue by jx-zhong-for-academic-purpose** [wanglimin/UntrimmedNet#23]
In your scripts anet_1.2_untrimmed_train_tvl1_list.txt and anet_1.2_untrimmed_train_rgb_list.txt, the number of flow frames is ALWAYS ONE LESS than RGB frames. Howerver, I extract flow&rgb images with TSN toolkits and find  the rgb images are JUST AS MANY AS flow images.  Why behind this matter?

**Comment by wanglimin** [comment]
Optical flow is calculated between two frames, and thereby its number should be less than RGB frames by one. In TSN toolkits, it should decrease the number of RGB frames by 1.

**Comment by jx-zhong-for-academic-purpose** [comment]
Get it，thank you~
