### ISSUE TITLE
Post-processing scheme for detection

### ISSUE THREAD

**Issue by hangg7** [wanglimin/UntrimmedNet#26]
Hi there,

I'm running into issues when trying to understand your detection scheme.

https://github.com/wanglimin/UntrimmedNet/blob/09cd15c8dfbed81ce884399ec6aa1c1a4e607896/matlab/thumos_detection.m#L87-L88

From my understanding `c_score` is a video level classification score after aggregating classification score with attention which you also used for recognition.

Could you please help me understand where does this `0.1` come from? Further more, I have used your released model to extract `test_score.mat`. In order to reproduce the result shown in the paper, I'm wondering if I can just feed it into your matlab module without modification?

**Comment by wanglimin** [comment]
Hi, in this demo code, we add a context modeling, where we use the classification score to help us filter some action categories. c_score is the classification score and if its classification score is lower than some threshold (0.1), we consider there is no action instance of this class in this video.

During paper submission, we used to attention weights to filter some background. After submission, we found this step is not necessary and thereby we did not release the code of using attention weights for filtering.

If your test_score.mat is correctly calculated, you can get the detection results of similar performance to our paper.

**Comment by hangg7** [comment]
Thanks for your quick response, closing it now.

**Comment by JacobKong** [comment]
Hey there, can you share your code for calculate the exact test_score for thumos_detection.m
That would really nice of you!!!
