### ISSUE TITLE
the problem about sampling

### ISSUE THREAD

**Issue by Yanchunswallow** [wanglimin/UntrimmedNet#27]
Hi, Limin
     Could you release the code of Shot-based sampling to get the clip proposals.
Thank you very much!

**Comment by wanglimin** [comment]
I used the following toolbox for shot boundary detection:

https://github.com/minhhoai2/MHLfuncs/tree/master/Video

**Comment by Yanchunswallow** [comment]
I am very glad to receive your reply!  @wanglimin 
I confuse what does each row represent in each ‘.txt’ file provided in your code? such as video_validation_0000001_window_shot.txt.  It will be helpful to me to find the problem why I got different result by using the toolbox you provided to get  shot boundary. 
Thank you very much!

**Comment by wanglimin** [comment]
The file is shot detection result. I think the video decoding may be different in your server to ours. You could see several example to see whether your detected shot boundary is correct.

**Comment by Yanchunswallow** [comment]
OK, I see, Thanks!
