### ISSUE TITLE
Performance of Spatial network

### ISSUE THREAD

**Issue by bityangke** [wanglimin/UntrimmedNet#4]
Hi，
I am working on similar project，and I want to cite your work in our paper.
And I need to know the performance of your SPATIAL network on thumos14 classification and detection task.
Could you please tell me about that?
Thanks in advance.

**Comment by wanglimin** [comment]
Hi, the classification performance is 0.7321 for soft selection and 0.7268 for hard selection. Currently, I do not have detection performance of spatial net at hand.

**Comment by bityangke** [comment]
Thank you very much!
It's very useful to me.
