### ISSUE TITLE
temporal annotations of acton instances

### ISSUE THREAD

**Issue by buaa-luzhi** [wanglimin/UntrimmedNet#6]
Hi, Limin
    "We do not have precise temporal annotations of action instances in training" in the paper.

      But, as far as I know,  Test_Data or Validation_Data has annotations in THUMOS2014. 
      Does that mean these annotations are not used in the training phase.
   
      Thank you very much,  looking forward to your reply!

**Comment by yjxiong** [comment]
You are correct. Temporal annotations are not used when training UntrimmedNets.

**Comment by buaa-luzhi** [comment]
@yjxiong 
Thank you very much, This is different from S-CNN training.

**Comment by yjxiong** [comment]
Note that UntrimmedNets deals with weakly supervised action recognition and detection, while S-CNN works on strongly supervised temporal action detection. These two works tackle different problems.

**Comment by buaa-luzhi** [comment]
yes, tahnk you!
Another question, only used validation data(1010 videos) to train models and test data(1574 videos) to evaluate performance, and in the data preprocessing to extract RGB and Optical Flow.

@yjxiong 
Thank you

**Comment by yjxiong** [comment]
What's the question?

**Comment by buaa-luzhi** [comment]
Oh, i  am so sorry .
The training  data only includes untrimmed videos(1010 videos in the THUMOS 2014) to train models? 
@yjxiong 
Thank you!

**Comment by yjxiong** [comment]
As stated in the paper

For comparison with other state-of-the-art methods
```
To get a fair comparison with other methods, we use the training (UCF101) and validation videos to learn UntrimmedNets on the THUMOS14 dataset.
```

While for the ablation studies, e.g. Table 1 and Fig. 3/4/5

```
We mainly use the validation data (1,010 videos) to train our models
```

**Comment by buaa-luzhi** [comment]
@yjxiong 
Thanks for your kindly help！
Thank you!

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.
