### ISSUE TITLE
About train data organization detail of THUMOS’14

### ISSUE THREAD

**Issue by bityangke** [wanglimin/UntrimmedNet#7]
When training on THUMOS14，trimmed videos are simply regarded as proposals.
That means, we need sample N trimmed videos (N stands for the number of proposals in an untrimmed video )to form a training sample?
Am I right?
Thanks !

**Comment by wanglimin** [comment]
Yes. First, you need to generate some proposals from each training sample. In our paper, we use two sampling methods: uniform sampling and shot based sampling.

**Comment by bityangke** [comment]
Hi Limin, thanks for your reply，
but what I want to know is about the trimmed videos（e.g. UCF101）.

**Comment by wanglimin** [comment]
In our paper, we perform two types of experiments on THUMOS14: (1) training on the validation data and evaluating on the test data. **In this case, we did not use any trimmed video. We simply use the sampling method to divide untrimmed video into clip proposals.** (2) training on the combination of THUMOS val data and UCF101, and evaluating on the test data. In this case, we used the trimmed video, namely UCF101.

**Comment by bityangke** [comment]
Thanks！
The UntrimmedNet can not be directly applied to UCF101.
Could you please give some clues about how to using the trimmed UCF101 videos to generate training samples for UntrimmedNet?

**Comment by wanglimin** [comment]
If you want to train on UCF101, you directly use the TSN framework. No need to use UntrimmedNet.

**Comment by bityangke** [comment]
OK, so I guess the training process of Untrimmed Net(on the combination of THUMOS val data and UCF101) includes following steps:
1)First, using UCF101 to train TSN
2)Second, using the trained TSN in step 1) to initialize the UntrimmedNet, then train UntrimmedNet on validation set. 
Am I right?

**Comment by wanglimin** [comment]
In fact, we use TSN train on the UCF101 and UntrimmedNet train on the Val data of THUMOS, where we make TSN and UntrimmedNet share the same weights (conv layers and fc layers for classification).

**Comment by bityangke** [comment]
Thank you very much for explaining these for me.
I think I got the details.
The training process of thumos is very complicated to implement for many deep learning frameworks.
Maybe alternate training of TSN and UntrimmedNet epoch by epoch is considerable.
