### ISSUE TITLE
About testset results of THUMOS14

### ISSUE THREAD

**Issue by bityangke** [wanglimin/UntrimmedNet#9]
Hi，Limin.
Where can I find the THUMOS14 frame-level results?
('~/code/temporal-segment-networks/THUMOS14_evalkit_20150930/test_score.mat')
Thanks!

**Comment by wanglimin** [comment]
This file is very big. We did not release it. 

We have released the model and you could calculate it by yourself.

**Comment by bityangke** [comment]
OK. Thank you very much!
